create table
  mainnet."Strategies" (
    address bytea not null,
    token bytea not null,
    name character varying not null,
    constraint "Strategies_pkey" primary key (address),
    constraint "Strategies_address_key" unique (address)
  ) tablespace pg_default;

create table
  mainnet."Deposits" (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    depositor bytea not null,
    amount numeric not null,
    block integer not null,
    log_index integer not null,
    strategy bytea not null,
    shares numeric not null,
    caller bytea not null,
    constraint "Deposits_pkey" primary key (id),
    constraint "Deposits_id_key" unique (id),
    constraint "Deposits_tx_key" unique (block, log_index)
  ) tablespace pg_default;

create table
  mainnet."LastIndexingStates" (
    id bigint generated by default as identity not null,
    key character varying not null,
    state integer not null,
    constraint "LastIndexingStates_pkey" primary key (id),
    constraint "LastIndexingStates_id_key" unique (id),
    constraint "LastIndexingStates_key_key" unique (key)
  ) tablespace pg_default;

create table
  mainnet."Pods" (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    block integer not null,
    address bytea not null,
    owner bytea not null,
    constraint "Pods_pkey" primary key (id),
    constraint "Pods_id_key" unique (id),
    constraint "Pods_address_key" unique (address)
  ) tablespace pg_default;

create table
  mainnet."ShareWithdrawals" (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    depositor bytea not null,
    nonce integer not null,
    strategy bytea not null,
    shares numeric not null,
    amount numeric null, -- only after withdrawn
    log_index integer not null,
    withdrawer bytea null, -- only after withdrawn
    delegated_address bytea null, -- only after withdrawn
    queued_block integer not null,
    withdraw_block integer null, -- only after withdrawn
    constraint "ShareWithdrawals_pkey" primary key (id),
    constraint "ShareWithdrawals_id_key" unique (id),
    constraint "ShareWithdrawals_block_log_index_key" unique (queued_block, log_index)
  ) tablespace pg_default;

create table
  mainnet."Validators" (
    index bigint not null,
    pubkey bytea not null,
    created_at timestamp with time zone not null default now(),
    balance numeric not null,
    withdrawal_address bytea not null,
    effective_balance numeric not null,
    activation_eligibility_epoch numeric not null,
    exit_epoch numeric not null,
    bls_epoch numeric null,
    slashed boolean not null,
    constraint "Validators_pkey" primary key (index),
    constraint "Validators_index_key" unique (index),
    constraint "Validators_pubkey_key" unique (pubkey)
  ) tablespace pg_default;
