name: Deploy

on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        required: true
        description: Git ref
        default: new

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-duration-seconds: 1200 # Set the session duration as needed
          role-session-name: RestakingDashboardGithubAction

      - name: Build
        run: |
          npm i
          npm run build

      - name: Update AWS S3 Bucket
        run: aws s3 sync ./dist ${{ secrets.AWS_S3_BUCKET_PROD }} --delete
