name: Deploy to Amplify Stage

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      ref:
        type: string
        required: true
        description: Git ref
        default: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: |
          URL="${{ secrets.AMPLIFY_WEBHOOK_STAGE }}"
          curl -X POST -d {} "$URL" -H "Content-Type: application/json"
