name: Deploy to amplify

on:
  push:
    branches: [ci/amplify-deploy]
  workflow_dispatch:
    inputs:
      ref:
        type: string
        required: true
        description: Git ref
        default: new

env:
  AWS_REGION: us-east-1
  AWS_S3_BUCKET_PROD: staging.restaking.info

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: deploy
      run: |
          URL="${{ secrets.AMPLIFY_WEBHOOK_NEW }}"
          curl -X POST -d {} "$URL" -H "Content-Type: application/json"
